version: 2
updates:
  # Client package.json
  - package-ecosystem: "npm"
    directory: "/src/client"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    versioning-strategy: "auto"
    groups:
      all-dependencies:
        patterns:
          - "*"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"

  # Server pyproject.toml
  - package-ecosystem: "pip"
    directory: "/src/server"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    versioning-strategy: "auto"
    groups:
      all-dependencies:
        patterns:
          - "*"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"



