version: 2
updates:
  # Root package.json
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    versioning-strategy: "auto"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"

  # Client package.json
  - package-ecosystem: "npm"
    directory: "/src/client"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    versioning-strategy: "auto"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"

  # Server pyproject.toml
  - package-ecosystem: "pip"
    directory: "/src/server"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    versioning-strategy: "auto"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"



