FROM ghcr.io/astral-sh/uv:python3.12-bookworm-slim

WORKDIR /app

COPY pyproject.toml uv.lock ./
RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/* && uv sync

ENV HOST 0.0.0.0
ENV PORT 80
CMD uv run uvicorn stac_fastapi.collection_discovery.app:app --host ${HOST} --port ${PORT} --log-level debug

