name: CI

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.8.*" 
    
      - name: Set up Python 
        run: uv python install 3.13
      
      - name: Install dependencies
        run: |
          uv sync

      - name: run pre-commit
        run: |
          uv run pre-commit run --all-files

  build-client:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      
      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Cache Node.js dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            node-modules-${{ runner.os }}-

      - name: Cache Yarn dependencies
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            .yarn
          key: yarn-cache-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-cache-${{ runner.os }}-

      - name: Install dependencies
        run: yarn install

      - name: Build client application
        run: yarn build

