name: CI

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.8.*"

      - name: Set up Python
        run: uv python install 3.13

      - name: Install dependencies
        run: |
          uv sync

      - name: run pre-commit
        run: |
          uv run pre-commit run --all-files

  build-client:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Set up node
        uses: actions/setup-node@v5
        with:
          node-version: 22

      - name: Cache Yarn dependencies
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            .yarn
          key: yarn-cache-v2-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-cache-v2-${{ runner.os }}-

      - name: Install dependencies
        run: yarn install

      - name: Check code formatting with prettier
        run: yarn prettier --check .

      - name: Build client application
        run: yarn build
