name: CI

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      
      - name: Install Poetry
        uses: Gr1N/setup-poetry@v9
        with:
          poetry-version: "1.8.0"

      - name: Set up Python
        uses: actions/setup-python@v5
        env:
          POETRY_VIRTUALENVS_IN_PROJECT: "true"
        with:
          python-version: "3.12"
          cache: poetry
          cache-dependency-path: src/server/poetry.lock

      - name: Install dependencies including dev dependencies
        working-directory: src/server
        run: poetry install --with dev

      - name: Run Tests
        working-directory: src/server
        run: poetry run pytest

  check-client-changes:
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.client_changes.outputs.changes }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Check for changes in client directory
        id: client_changes
        run: |
          if git diff --quiet HEAD^ HEAD -- src/client; then
            echo "changes=false" >> $GITHUB_OUTPUT
          else
            echo "changes=true" >> $GITHUB_OUTPUT
          fi

  build-client:
    needs: [check-client-changes]
    runs-on: ubuntu-latest
    if: needs.check-client-changes.outputs.changes == 'true'
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      
      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Cache Node.js dependencies
        uses: actions/cache@v4
        with:
          path: src/client/node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            node-modules-${{ runner.os }}-

      - name: Cache Yarn dependencies
        uses: actions/cache@v4
        with:
          path: |
            src/client/node_modules
            src/client/.yarn
          key: yarn-cache-${{ runner.os }}-${{ hashFiles('src/client/yarn.lock') }}
          restore-keys: |
            yarn-cache-${{ runner.os }}-

      - name: Install dependencies
        working-directory: src/client
        run: yarn install

      - name: Build client application
        working-directory: src/client
        run: yarn build

  publish:
    needs: [test]
    runs-on: ubuntu-latest
    if: startsWith(github.event.ref, 'refs/tags') || github.event_name == 'release'
    environment:
      name: pypi
      url: https://pypi.org/p/federated-collection-discovery
    permissions:
      id-token: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      
      - name: Install Poetry
        uses: Gr1N/setup-poetry@v9
        with:
          poetry-version: "1.8.0"

      - name: Set up Python
        uses: actions/setup-python@v5
        env:
          POETRY_VIRTUALENVS_IN_PROJECT: "true"
        with:
          python-version: "3.12"
          cache: poetry
          cache-dependency-path: src/server/poetry.lock

      - name: Set tag version
        id: tag
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Set module version
        working-directory: src/server
        id: module
        run: echo "version=$(python federated_collection_discovery/__init__.py)" >> $GITHUB_ENV

      - name: Build package
        if: env.tag == env.version
        working-directory: src/server
        run: |
          poetry self add poetry-version-plugin
          poetry build

      - name: Publish to pypi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: src/server/dist/
